name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            python3-dev \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo6 \
            cmake \
            libffi-dev \
            git \
            unzip \
            openjdk-11-jdk

    - name: Install Cython and Buildozer
      run: |
        pip3 install cython
        pip3 install --upgrade buildozer kivy

    - name: Install Android SDK
      run: |
        mkdir -p ~/android-sdk
        cd ~/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        yes | ./cmdline-tools/bin/sdkmanager --sdk_root=~/android-sdk --licenses
        ./cmdline-tools/bin/sdkmanager --sdk_root=~/android-sdk "platform-tools" "build-tools;34.0.0" "platforms;android-34"

    - name: Install Android NDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        wget https://dl.google.com/android/repository/android-ndk-r26c-linux.zip
        unzip android-ndk-r26c-linux.zip -d ~/.buildozer/android/platform/
        mv ~/.buildozer/android/platform/android-ndk-r26c ~/.buildozer/android/platform/android-ndk-r26.2.11394342

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: snake.apk
        path: bin/*.apk
