name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            python3-dev \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo6 \
            cmake \
            libffi-dev \
            git \
            unzip \
            openjdk-11-jdk

    - name: Install Cython
      run: pip3 install cython

    - name: Install Android SDK and Build-Tools
      run: |
        mkdir -p ~/android-sdk
        cd ~/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        yes | ./cmdline-tools/bin/sdkmanager --sdk_root=~/android-sdk --licenses
        ./cmdline-tools/bin/sdkmanager --sdk_root=~/android-sdk "platform-tools" "build-tools;34.0.0" "platforms;android-36"

        # Явная загрузка NDK
        wget https://dl.google.com/android/repository/android-ndk-r26.2.11394342-linux.zip
        unzip android-ndk-r26.2.11394342-linux.zip -d ~/.buildozer/android/platform/

        # Проверка наличия aidl
        ls ~/android-sdk/build-tools/36.0.0/aidl || echo "Aidl not found!"

    - name: Set environment variables
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        echo "$HOME/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH  # Добавлен путь к build-tools

    - name: Install Buildozer and Kivy
      run: pip install --upgrade buildozer kivy

    - name: Build APK
      run: |        
         buildozer android debug
         
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: snake.apk
        path: bin/*.apk
