name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip autoconf libtool pkg-config zlib1g-dev

      - name: Accept licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Build APK
        run: |
          pip install cython buildozer
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
